/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Aula_ArrayList_09_10;

import java.util.ArrayList;
import java.util.Scanner;

public class App {
    
    public static void main(String[] args) {
        ArrayList<String> arr = new ArrayList<>();
        Scanner scan = new Scanner(System.in);
        boolean continuar = true;
        do {
            System.out.println("Actions:"
                    + "\n1 -> adicionar"
                    + "\n2 -> mostrar"
                    + "\n3 -> sair");
            System.out.println("Acao: ");
            
            String action = scan.nextLine();
           
            switch (action) {
                case "1":
                    System.out.println("Digite o nome: ");
                    String nome = scan.nextLine();
                    arr.add(nome);
                    System.out.println("Continuar...");
                    
                    break;
                case "2":
                    System.out.println(arr);;
                    System.out.println("Continuar...");
                    break;
                    
                case "3":
                    System.out.println("Saindo...");
                    continuar = false;
                    break;
                default:
                    throw new AssertionError();
            }
        } while(continuar);

//        // Estamos declarando um arraylit que ace8ita String
//         ArrayList<String> nomes = new ArrayList<>(); // Criar um ArrayList
//        // Adicionar elementos
//        nomes.add("Gregori");
//        nomes.add("Kauan");
//        nomes.add("Ederson");
//        nomes.add("Angelo");
//        
//
//        // Imprimir o ArrayList
//        System.out.println(nomes);
//        
//        // Pra remover, usamos .remove(indice)
//        nomes.remove(0);
//        System.out.println(nomes);
//        
//        // O metodo .add permite adicionar o item no indice especificado
//        nomes.add(1, "Bruno");
//        System.out.println(nomes);
//        
//        // O metodo .remove permite remover por valor tambem
//        // Ele remove o primeiro item que tiver aquele valor
//        nomes.remove("Bruno");
//        System.out.println(nomes);
//        
//        // o metodo .get(indice) me permite acesar um valor dentro do arraylist
//        String elemento = nomes.get(0); // Kauan
//        System.out.println(elemento);
//        
//        // o metodo .indexOf(valor) retorna o indice do item que eu solicitei
//        // retorna -1 caso o ArrayList não tenha esse item
//        int indiceNome = nomes.indexOf("Ederson");
//        System.out.println(indiceNome);
//        
//        // o metodo .lastIndexOf(valor) retorna o indice do ultimo item com o valor que eu solicitei
//        // retorna -1 caso o ArrayList não tenha esse item
//        int ultimoIndiceNome = nomes.lastIndexOf("Ederson");
//        System.out.println(ultimoIndiceNome);
//        
//        //
//        nomes.set(2, "Leo");
//        System.out.println(nomes);
//        
//        // O método size() retorna a quantidade de itens do Arraylist
//        int tamanho = nomes.size();
//        System.out.println(tamanho);
//        
//        // O método isEmpty() retirna 'true' se o ArrayList estiver vazio
//        // e retorna 'false' se ele tiver algum item
//        boolean verificar = nomes.isEmpty();
//        System.out.println(verificar);
//        
//        // O método .contais(valor) verifica se o ArrauyList tem um determinado item ou não
//        // retorna true or false
//        boolean contain = nomes.contains("aaaaaa");
//        System.out.println(contain);
//        
//        // O método clear() remove todos os itens do ArrayList
//        // não retorna nada
//        nomes.clear();
//        System.out.println(nomes);
//        
//        ArrayList<Integer> numeros = new ArrayList<>();
//        
//        numeros.add(1);
//        numeros.add(2);
//        numeros.add(3);
//        numeros.add(4);        
//        numeros.add(4);
//
//        System.out.println(numeros);
//               
//        numeros.remove(1);
//        
//        System.out.println(numeros);
//
//        numeros.add(0, 1);
//        
//        System.out.println(numeros);
//        
//        System.out.println(numeros.get(1));
//        
//        numeros.set(1, 3);
//        
//        System.out.println(numeros);
//        
//        System.out.println(numeros.indexOf(1));
//        
//        numeros.clear();
//        
//        System.out.println(numeros);
                
    }
}
