/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package Aula_javaSwim_17_10;

import javax.swing.JOptionPane;

/**
 *
 * @author EDERSONDASILVASCHMID
 */
public class teste extends javax.swing.JFrame {

    /** Creates new form teste */
    public teste() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        conteiner = new javax.swing.JPanel();
        nu1 = new javax.swing.JTextField();
        labelLogin = new javax.swing.JLabel();
        buttonSoma = new javax.swing.JButton();
        nu2 = new javax.swing.JTextField();
        result = new javax.swing.JLabel();
        buttonMultiplicacao = new javax.swing.JButton();
        buttonDivisao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        conteiner.setBackground(new java.awt.Color(204, 255, 255));

        nu1.setText("Digite um numero...");
        nu1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nu1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nu1FocusLost(evt);
            }
        });
        nu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nu1ActionPerformed(evt);
            }
        });
        nu1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nu1KeyPressed(evt);
            }
        });

        labelLogin.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        labelLogin.setForeground(new java.awt.Color(0, 255, 102));
        labelLogin.setText("Calculadora");
        labelLogin.setPreferredSize(new java.awt.Dimension(80, 16));

        buttonSoma.setBackground(new java.awt.Color(0, 102, 204));
        buttonSoma.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        buttonSoma.setText("+");
        buttonSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSomaActionPerformed(evt);
            }
        });

        nu2.setText("Digite um numero...");
        nu2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nu2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nu2FocusLost(evt);
            }
        });
        nu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nu2ActionPerformed(evt);
            }
        });

        result.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        result.setText("Resultado: ");

        buttonMultiplicacao.setBackground(new java.awt.Color(0, 102, 204));
        buttonMultiplicacao.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        buttonMultiplicacao.setText("X");
        buttonMultiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMultiplicacaoActionPerformed(evt);
            }
        });

        buttonDivisao.setBackground(new java.awt.Color(0, 102, 204));
        buttonDivisao.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        buttonDivisao.setText("/");
        buttonDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDivisaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout conteinerLayout = new javax.swing.GroupLayout(conteiner);
        conteiner.setLayout(conteinerLayout);
        conteinerLayout.setHorizontalGroup(
            conteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conteinerLayout.createSequentialGroup()
                .addGroup(conteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(conteinerLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(conteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nu1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nu2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(result)))
                    .addGroup(conteinerLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(labelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(conteinerLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(buttonSoma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonMultiplicacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonDivisao)))
                .addContainerGap(524, Short.MAX_VALUE))
        );
        conteinerLayout.setVerticalGroup(
            conteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conteinerLayout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(labelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nu1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(nu2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(conteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonDivisao)
                    .addComponent(buttonMultiplicacao)
                    .addComponent(buttonSoma))
                .addGap(18, 18, 18)
                .addComponent(result)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(conteiner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(conteiner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSomaActionPerformed

        int numero1 = Integer.parseInt(this.nu1.getText());
        int numero2 = Integer.parseInt(this.nu2.getText());
        
        String textoResult = "Resultado: ";
        this.result.setText(textoResult + (numero1 + numero2));
    }//GEN-LAST:event_buttonSomaActionPerformed

    private void nu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nu1ActionPerformed

    private void nu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nu2ActionPerformed

    private void nu1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nu1FocusGained
        if("Digite um numero...".equals(this.nu1.getText())) {
            this.nu1.setText("");
        }
    }//GEN-LAST:event_nu1FocusGained

    private void nu1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nu1FocusLost
       if(this.nu1.getText().equals("")) {
           this.nu1.setText("Digite um numero...");
       }
    }//GEN-LAST:event_nu1FocusLost

    private void nu2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nu2FocusGained
        if("Digite um numero...".equals(this.nu2.getText())) {
                this.nu2.setText("");
        }
    }//GEN-LAST:event_nu2FocusGained

    private void nu2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nu2FocusLost
        if(this.nu2.getText().equals("")){
            this.nu2.setText("Digite um numero...");
        }
    }//GEN-LAST:event_nu2FocusLost

    private void nu1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nu1KeyPressed
        
    }//GEN-LAST:event_nu1KeyPressed

    private void buttonMultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMultiplicacaoActionPerformed
        double numero1 = Double.parseDouble(this.nu1.getText());
        double numero2 = Double.parseDouble(this.nu2.getText());
        
        String textoResult = "Resultado: ";
        this.result.setText(textoResult + (numero1 * numero2));
    }//GEN-LAST:event_buttonMultiplicacaoActionPerformed

    private void buttonDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDivisaoActionPerformed
        double numero1 = Double.parseDouble(this.nu1.getText());
        double numero2 = Double.parseDouble(this.nu2.getText());
        
        String textoResult = "Resultado: ";
        if(numero1 != 0 && numero2 != 0) {
            this.result.setText(textoResult + (numero1 / numero2));
        } else {
            JOptionPane.showConfirmDialog(this, "Divisao por 0 nao permitidas");
        }
    }//GEN-LAST:event_buttonDivisaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDivisao;
    private javax.swing.JButton buttonMultiplicacao;
    private javax.swing.JButton buttonSoma;
    private javax.swing.JPanel conteiner;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JTextField nu1;
    private javax.swing.JTextField nu2;
    private javax.swing.JLabel result;
    // End of variables declaration//GEN-END:variables

}
