/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Aula_20_10;

import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author EDERSONDASILVASCHMID
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
        
        stateOptions.addItem("RJ");
        stateOptions.addItem("RN");
        stateOptions.addItem("RS");
        
//        Inicia o programa com yesRadio selecionado
        yesRadio.setSelected(true);        
        yesWorkRadio.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        nameField = new javax.swing.JTextField();
        stateOptions = new javax.swing.JComboBox<>();
        stateLabel = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        programmingLanguages = new javax.swing.JLabel();
        jsBox = new javax.swing.JCheckBox();
        tsBox = new javax.swing.JCheckBox();
        pyBox = new javax.swing.JCheckBox();
        javaBox = new javax.swing.JCheckBox();
        phpBox = new javax.swing.JCheckBox();
        yesRadio = new javax.swing.JRadioButton();
        noRadio = new javax.swing.JRadioButton();
        labelProgramming = new javax.swing.JLabel();
        labelStudent = new javax.swing.JLabel();
        yesWorkRadio = new javax.swing.JRadioButton();
        noWorkRadio = new javax.swing.JRadioButton();
        sometimesWorkRadio1 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        nameField.setText("Your full name...");
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        stateOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateOptionsActionPerformed(evt);
            }
        });

        stateLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        stateLabel.setForeground(new java.awt.Color(0, 0, 0));
        stateLabel.setText("State");

        btnRegister.setBackground(new java.awt.Color(255, 255, 255));
        btnRegister.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(51, 153, 255));
        btnRegister.setText("Registre");
        btnRegister.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255), 2));
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        programmingLanguages.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        programmingLanguages.setForeground(new java.awt.Color(0, 0, 0));
        programmingLanguages.setText("Programming Languages");

        jsBox.setForeground(new java.awt.Color(102, 102, 255));
        jsBox.setText("JS");

        tsBox.setForeground(new java.awt.Color(102, 102, 255));
        tsBox.setText("TS");

        pyBox.setForeground(new java.awt.Color(102, 102, 255));
        pyBox.setText("PY");

        javaBox.setForeground(new java.awt.Color(102, 102, 255));
        javaBox.setText("JAVA");

        phpBox.setForeground(new java.awt.Color(102, 102, 255));
        phpBox.setText("PHP");

        buttonGroup1.add(yesRadio);
        yesRadio.setText("Yes");

        buttonGroup1.add(noRadio);
        noRadio.setText("No");

        labelProgramming.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        labelProgramming.setForeground(new java.awt.Color(0, 0, 0));
        labelProgramming.setText("Are you a student?");

        labelStudent.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        labelStudent.setForeground(new java.awt.Color(0, 0, 0));
        labelStudent.setText("Do you use programming on you work?");

        buttonGroup2.add(yesWorkRadio);
        yesWorkRadio.setText("Yes");

        buttonGroup2.add(noWorkRadio);
        noWorkRadio.setText("No");

        buttonGroup2.add(sometimesWorkRadio1);
        sometimesWorkRadio1.setText("sometimes");
        sometimesWorkRadio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sometimesWorkRadio1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(labelProgramming)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yesRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(noRadio))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(programmingLanguages)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jsBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tsBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pyBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(javaBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(phpBox))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(stateLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stateOptions, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(nameField)
                            .addComponent(btnRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(labelStudent)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yesWorkRadio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(noWorkRadio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sometimesWorkRadio1)))))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stateOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(programmingLanguages)
                    .addComponent(jsBox)
                    .addComponent(tsBox)
                    .addComponent(pyBox)
                    .addComponent(javaBox)
                    .addComponent(phpBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelProgramming)
                    .addComponent(yesRadio)
                    .addComponent(noRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yesWorkRadio)
                    .addComponent(noWorkRadio)
                    .addComponent(labelStudent)
                    .addComponent(sometimesWorkRadio1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(btnRegister)
                .addGap(89, 89, 89))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stateOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateOptionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateOptionsActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
////        1 - Lê nome 
//        String name = nameField.getText();
////        2 - Verifica o estado selecionado
//        String state = stateOptions.getSelectedItem().toString();
////        3- Abre uma janela informando os dados
//        String message = "";
////        
//        switch (state) {
//            case "RS":
//                message = "You are Gaucho!";
//                break;
//            case "RJ": 
//                message = "You are Carioca";
//                break;
//            case "RN":
//                message = "You are Rio Nordense";
//        }
//        JOptionPane.showMessageDialog(this, message);

//        showProgrammingLanguages();
        student();        
        programmingWork();
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void sometimesWorkRadio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sometimesWorkRadio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sometimesWorkRadio1ActionPerformed

    private void showProgrammingLanguages() {
//        Verifica se  o jsBox esta selecionado
//        boolean jsSelected = jsBox.isSelected();
//        boolean tsSelected = tsBox.isSelected();
//        boolean pySelected = pyBox.isSelected();
//        boolean javaSelected = javaBox.isSelected();
//        boolean phpSelected = phpBox.isSelected();
//        
//        String message = "You know these languages: ";
//        
//        if (jsSelected) message += "\n→ JavaScript";
//        if (tsSelected) message += "\n→ TypeScript";
//        if (pySelected) message += "\n→ Pyton";        
//        if (javaSelected) message += "\n→ Java";
//        if (phpSelected) message += "\n→ PHP";
//
//        JOptionPane.showMessageDialog(this, message);
  
//          Array que contem todos os checkBoxes
        JCheckBox[] checks = { jsBox, tsBox, pyBox, javaBox, phpBox };
//          Array que contem as string
        String[] languages = { "JavaScript", "TypeScript", "Python", "Java", "PHP" };
        
        String message = "You know these languages: ";
        
        for(int i = 0; i < checks.length; i++) {
            if(checks[i].isSelected()) {
                message += "\n • " + languages[i];
            }
        }
        
        JOptionPane.showMessageDialog(this, message);
    }
    
    private void student() {
        boolean isStudent = yesRadio.isSelected();        
        
        if (isStudent) { 
            System.out.println("You are student!");

        } else {
            System.out.println("You aren't student!");
        }
    }
    
    private void programmingWork() {
        boolean yes = yesWorkRadio.isSelected();
        boolean no = noWorkRadio.isSelected();
        
        if (yes) {
            System.out.println("You are programmer!");
        } else if (no) {
            System.out.println("You are't programmer!");
        } else {
            System.out.println("You are tramp!");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox javaBox;
    private javax.swing.JCheckBox jsBox;
    private javax.swing.JLabel labelProgramming;
    private javax.swing.JLabel labelStudent;
    private javax.swing.JTextField nameField;
    private javax.swing.JRadioButton noRadio;
    private javax.swing.JRadioButton noWorkRadio;
    private javax.swing.JCheckBox phpBox;
    private javax.swing.JLabel programmingLanguages;
    private javax.swing.JCheckBox pyBox;
    private javax.swing.JRadioButton sometimesWorkRadio1;
    private javax.swing.JLabel stateLabel;
    private javax.swing.JComboBox<String> stateOptions;
    private javax.swing.JCheckBox tsBox;
    private javax.swing.JRadioButton yesRadio;
    private javax.swing.JRadioButton yesWorkRadio;
    // End of variables declaration//GEN-END:variables
}
